ARG PYTHON_VERSION=3.10.5

FROM python:$PYTHON_VERSION-bullseye

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONFAULTHANDLER=1 \
    POETRY_VERSION=1.1.14 \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PATH=/root/.local/bin:$PATH

RUN curl -sSL https://install.python-poetry.org | python - \
    && poetry --version
